config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cats#index'

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_comments, only: [:create]
  resources :articles, only: [:show, :new, :create, :edit, :update]
  resources :article_comments, only: [:create]
  resources :sessions, only: [:new, :create]
  resources :contacts, only: [:index, :new, :create, :destroy]
  resources :cat_personality_test, only: [:index, :new, :create, :show]
  resources :about_me, only: [:index]

  get 'contacts/destroy_all', to: 'contacts#destroy_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :article_body
  has_many :article_comments, dependent: :destroy
  extend FriendlyId
  friendly_id  :slug

  default_scope { order(created_at: :desc) }
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  has_rich_text :body
  validates :body, presence: true
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_rich_text :article
  has_many :videos, dependent: :destroy
  has_many :cat_comments, dependent: :destroy
  extend FriendlyId
  friendly_id :slug
end

app/models/cat_comment.rb
class CatComment < ApplicationRecord
  belongs_to :cat
  has_rich_text :body
  validates :body, presence: true
end

app/models/cat_count.rb
class CatCount < ApplicationRecord
end

app/models/cat_personality.rb
class CatPersonality < ApplicationRecord
  extend FriendlyId
  friendly_id :slug
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def admin?
    self.role == 'admin'
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :cat
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController

  def index
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :js_css
  before_action :admin, only: [:edit, :update, :new, :create]

  # def index
  #   @articles = Article.paginate(page: params[:page], per_page: 1 ).order('created_at DESC')
  #   @articles = [] if @articles.length == 0
  # end

  def show
    #@article = Article.find_by_id(params[:id])
    @article = Article.friendly.find(params[:id])
    @article_comments = ArticleComment.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @article_comment = ArticleComment.new
    @twitterTitle = @article.title
    @twitterURL = "https://www.felinesfancy.com/articles/#{@article.slug}"
    @twitterImage = @article.image
    @twitterDescription = @article.short_description
    @publication_date = "#{@article.created_at.year}-#{@article.created_at.month}-#{@article.created_at.day}"
    @date_modified = "#{@article.updated_at.year}-#{@article.updated_at.month}-#{@article.updated_at.day}"
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create!(article_params)
    redirect_to article
  end

  def edit
    @article = Article.friendly.find(params[:id])
  end

  def update
    #article = Article.find_by_id(params[:id])
    article = Article.friendly.find(params[:id])
    article.update(article_params)
    redirect_to article
  end


  private

  def article_params
    params.require(:article).permit(:title, :image, :article_body, :short_description, :slug)
  end

  def js_css
    @js_css = {css: "article", js: "article"}
  end

  def admin
    unless current_user && current_user.admin?
      flash[:danger] = "How dare you use your guile tactics on us!"
      redirect_to '/cats'
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :js_css
  before_action :index_js_css, only: [:index]
  before_action :admin, only: [:edit, :update, :new, :create]

  def index
    @cats = Cat.paginate(page: params[:cat_page], per_page: 4 ).order('created_at ASC')
    @articles = Article.paginate(page: params[:page], per_page: 3 ).order('created_at ASC')
    @homepage = true
  end

  def show
    #@cat = Cat.find_by_id(params[:id])
    #@cat = Cat.friendly.find_by_id(params[:id])
    @cat = Cat.friendly.find(params[:id])
    puts "@cat"
    puts @cat
    @video_prefix = "https://www.youtube.com/embed/"
    @first_video = Video.where(cat_id: @cat).first
    @videos = Video.where(cat_id: @cat)[1..4]
    @cat_comments = CatComment.paginate(page: params[:page], per_page: 5 ).order('created_at DESC')
    @cat_comment = CatComment.new
    @twitterTitle = @cat.title
    @twitterURL = "https://www.felinesfancy.com/cats/#{@cat.slug}"
    @twitterImage = 'media/images/cats/' + @cat.image
    @twitterDescription = @cat.short_description
    @publication_date = "#{@cat.created_at.year}-#{@cat.created_at.month}-#{@cat.created_at.day}"
    @date_modified = "#{@cat.updated_at.year}-#{@cat.updated_at.month}-#{@cat.updated_at.day}"
  end

  def new
    @cat = Cat.new
  end

  def create
    cat = Cat.create!(cat_params)
    redirect_to cat
  end

  def edit
    #@cat = Cat.find_by_id(params[:id])
    @cat = Cat.friendly.find(params[:id])
  end

  def update
    #cat = Cat.find_by_id(params[:id])
    cat = Cat.friendly.find(params[:id])
    cat.update(cat_params)
    redirect_to cat
  end


  private

  def cat_params
    params.require(:cat).permit(:title, :image, :short_description, :article, :slug)
  end

  def js_css
    @js_css = {css: "cat", js: "cat"}
  end

  def index_js_css
    @index = {css: "article", js: "article"}
  end

  def admin
    unless current_user && current_user.admin?
      flash[:danger] = "How dare you use your guile tactics on us!"
      redirect_to '/cats'
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include Jsonld
  before_action :admin, only: [:index, :destroy, :destroy_all]

  def index
    @contacts = Contact.all.order('created_at DESC')
  end

  def new
    @contact = Contact.new
    json_ld('Contact Us', 'media/images/header/cat.png',
      '2019-12-15 22:18:04 UTC', '2019-12-15 22:18:04 UTC', new_contact_path,
      "Contact Feline's Fancy or give some feedback")
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    redirect_to root_path
  end

    def destroy
      @contact = Contact.find(params[:id])
      @contact.destroy

      redirect_to contacts_path
    end

    def destroy_all
      Contact.destroy_all
      redirect_to contacts_path
    end


  private

  def contact_params
    params.require(:contact).permit(:email, :body)
  end

  def admin
    unless current_user && current_user.admin?
      flash[:danger] = "How dare you use your guile tactics on us!"
      redirect_to '/cats'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @meta_tag= "noindex"
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/cats'
    else
      redirect_to new_session_path
      flash[:alert] = "Oops.. Houston, we have a problem..."
    end
  end

  def destroy
    @meta_tag= "noindex"

    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cat_comments_helper.rb
module CatCommentsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :short_description %>
    <%= form.text_field :short_description %>

    <%= form.label :image %>
    <%= form.text_field :image %>

    <%= form.label :slug %>
    <%= form.text_field :slug %>

    <%= form.label :article_body %>
    <%= form.rich_text_area :article_body %>

    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'articles/form' %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="article">
    <h2><%= article.title %></h2>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= render 'articles/form' %>

app/views/articles/show.html.erb
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>
<div class="article">
  <div class="article__top">
    <h1><%= @article.title %></h1>
  </div>
  <div class="article__article">
    <%= @article.article_body %>
  </div>
  <div class="article__comment">
    <center><h5>Share</h5></center>
    <ul class="share-buttons">
      <li class="fb-share-button" data-href="http://www.felinesfancy.com/" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.felinesfancy.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></li>
      <li><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></li>
    </ul>
    <center><h5>Tell Us Your Thoughts!</h5></center>

    <%= render 'article_comments/form' %>

    <% if @article_comments %>
      <div class="article__comments">
        <% @article_comments.each do |comment| %>
          <div class="comment">
            <%= comment.body %>
          </div>
        <% end %>

        <%= will_paginate @article_comments, class: "digg_pagination" %>
      </div>
    <% end %>
  </div>
  <div class="scroll_buttons" data-controller="article-scroll">
    <div class="scroll_bottom">
      <button class="btn" type="button" name="scroll_bottom" data-action="click->article-scroll#scrollBottom">
        Scroll Bottom &#9660;
      </button>
    </div>
    <div class="scroll_top">
      <button class="btn" type="button" name="scroll_top" data-action="click->article-scroll#scrollTop">
        Scroll Top &#9650;
      </button>
    </div>
  </div>
</div>

app/views/cats/_form.html.erb
<%= form_for(@cat) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :image %>
    <%= form.text_field :image %>

    <%= form.label :thumbnail %>
    <%= form.text_field :thumbnail %>

    <%= form.label :short_description %>
    <%= form.text_area :short_description %>

    <%= form.label :slug %>
    <%= form.text_field :slug %>

    <%= form.label :article %>
    <%= form.rich_text_area :article %>

    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<%= render 'cats/form' %>

app/views/cats/index.html.erb
<div class="index">
  <h2 class="article_header">Articles</h2>
  <div class="index__articles">
    <% @articles.each do |article| %>
      <%= link_to article_path(article), class: "blog-link" do %>
        <div class="blog-card">
            <img class="blog-img" src="<%= asset_pack_path article.image %>" />
            <div class="text-overlay">
              <h2><%= article.title %></h2>
              <p>
                <%= article.short_description.truncate(138) if article.short_description %>
                <i>Read More</i>
              </p>

            </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= will_paginate @articles, class: "digg_pagination" %>

  <h2 class="cat_header">Cat Breeds</h2>
  <div class="index__cats">
    <% @cats.each do |cat| %>
      <%= link_to cat_path(cat) do %>
        <div class="cat-blog-card">
            <img class="blog-img" src="<%= asset_pack_path 'media/images/cats/' + cat.image %>" />
          <div class="cat-text-overlay">
            <h2><%= cat.title.sub(" Cat: Facts & Trivia", "") %></h2>
            <p>
              <%= cat.short_description.truncate(83) if cat.short_description %>
              <i>Read More</i>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= will_paginate @cats, class: "digg_pagination", param_name: :cat_page %>
</div>

app/views/cats/new.html.erb
<%= render 'cats/form' %>

app/views/cats/show.html.erb
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>
<div class="article" data-controller="accordian">
  <div class="article__top">
    <div class="cat__header">
      <%# image_pack_tag 'media/images/cats/' + @cat.image %>
      <img src="<%= asset_pack_path 'media/images/cats/' + @cat.image %>"
        data-pin-url="http://www.felinesfancy.com/cats/<%= @cat.id %>"
        data-pin-description="<%= @cat.title %>"
      >
      <h1><%= @cat.title %></h1>
    </div>
    <div class="article__short_description"><%= @cat.short_description %></div>
  </div>

  <!-- <center><h5>Tell Us Your Thoughts!</h5></center> -->

  <!-- <div class="article__article_header">
    <button class="article__button btn" type="button" name="article_button"
      data-target="accordian.article_header" data-action="click->accordian#expandShrinkArticle"
    >
      <h3>Click for full Description</h3>
    </button>
  </div> -->
  <div data-target="accordian.article" class="article__article">
    <%= @cat.article %>
  </div>
  <!-- <div class="article__meta">
    <button class="youtube__button btn" type="button" name="youtube_button"
      data-target="accordian.youtube_header" data-action="click->accordian#expandShrinkYoutube"
    >
      <h4>Show Videos</h4>
    </button>
    <button class="socialrank__button btn" type="button" name="socialrank_button"
      data-target="accordian.socialrank_header" data-action="click->accordian#expandShrinkSocialrank"
    >
      <h4>Show Rank</h4>
    </button>
  </div> -->

  <% if @first_video && @videos %>
    <div class="youtube" data-target="accordian.first_video">
      <div class="videoWrapper first_video">
        <iframe src="<%= @video_prefix + @first_video.video_id %>"
          frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
      </div>
      <div data-target="accordian.youtube" class="article__youtube">
        <h5>More Interesting Videos about the <%= @cat.title.sub(": Facts & Trivia", "") %> !</h5>
        <% @videos.each do |video| %>
          <div class="cat_videos">
            <iframe src="<%= @video_prefix + video.video_id %>"
              frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <!-- <div data-target="accordian.socialrank" class="article__socialrank">
    <script type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1845_RC03/embed_loader.js">
    </script>
    <script type="text/javascript">
      trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"<%# @cat.social %>","geo":"","time":"today 1-m"}],"category":0,"property":""}, {"exploreQuery":"date=today%201-m&q=%2Fm%2F0132vv","guestPath":"https://trends.google.com:443/trends/embed/"});
    </script>
  </div> -->

  <center><h5>Share</h5></center>
  <ul class="share-buttons">
    <li class="fb-share-button" data-href="http://www.felinesfancy.com/" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.felinesfancy.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></li>
    <li><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></li>
  </ul>

  <div class="article__comment">
    <h5>Tell Us About Your <%= @cat.title.sub(": Facts & Trivia", "") %></h5>
    <%= render 'cat_comments/form' %>

    <% if @cat_comments %>
      <div class="article__comments">
        <% @cat_comments.each do |comment| %>
          <div class="comment">
            <%= comment.body %>
          </div>
        <% end %>

        <%= will_paginate @cat_comments, class: "digg_pagination" %>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<%= link_to 'Destroy All', contacts_destroy_all_path(),
            # method: :delete,
            data: { confirm: 'Are you sure?' } %>

<% @contacts.each do |contact| %>
  <p>
    <%= contact.created_at %>
  </p>
  <p>
    <%= contact.body %>
  </p>
  <p>
    <%= contact.email %>
  </p>
  <%= link_to 'Destroy', contact_path(contact),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  <br>
<% end %>

app/views/contacts/new.html.erb
<%= form_for :contact, url: contacts_path do |f| %>
<div id="contact">
  <div class="contact_form">
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email, class: "form-control" %>
    </p>

    <p id="contact-text">
      <%= f.label :body, "Message" %><br>
      <%= f.text_area :body, class: "form-control contact-form" %>
    </p>

    <p class="text-center">
      <%= f.submit "Contact Me", class: "btn btn-contact" %>
    </p>
  </div>
</div>
<% end %>