config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cats#index'

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_comments, only: [:create]
  resources :articles, only: [:show, :new, :create, :edit, :update]
  resources :article_comments, only: [:create]
  resources :sessions, only: [:new, :create]
  resources :contacts, only: [:index, :new, :create, :destroy]
  resources :cat_personality_test, only: [:index, :new, :create, :show]
  resources :about_me, only: [:index]

  get 'contacts/destroy_all', to: 'contacts#destroy_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :article_body
  has_many :article_comments, dependent: :destroy
  extend FriendlyId
  friendly_id  :slug

  default_scope { order(created_at: :desc) }
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  has_rich_text :body
  validates :body, presence: true
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_rich_text :article
  has_many :videos, dependent: :destroy
  has_many :cat_comments, dependent: :destroy
  extend FriendlyId
  friendly_id :slug
end

app/models/cat_comment.rb
class CatComment < ApplicationRecord
  belongs_to :cat
  has_rich_text :body
  validates :body, presence: true
end

app/models/cat_count.rb
class CatCount < ApplicationRecord
end

app/models/cat_personality.rb
class CatPersonality < ApplicationRecord
  extend FriendlyId
  friendly_id :slug
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def admin?
    self.role == 'admin'
  end

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :cat
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController

  def index
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :js_css
  before_action :admin, only: [:edit, :update, :new, :create]

  # def index
  #   @articles = Article.paginate(page: params[:page], per_page: 1 ).order('created_at DESC')
  #   @articles = [] if @articles.length == 0
  # end

  def show
    #@article = Article.find_by_id(params[:id])
    @article = Article.friendly.find(params[:id])
    @article_comments = ArticleComment.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @article_comment = ArticleComment.new
    @twitterTitle = @article.title
    @twitterURL = "https://www.felinesfancy.com/articles/#{@article.slug}"
    @twitterImage = @article.image
    @twitterDescription = @article.short_description
    @publication_date = "#{@article.created_at.year}-#{@article.created_at.month}-#{@article.created_at.day}"
    @date_modified = "#{@article.updated_at.year}-#{@article.updated_at.month}-#{@article.updated_at.day}"
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create!(article_params)
    redirect_to article
  end

  def edit
    @article = Article.friendly.find(params[:id])
  end

  def update
    #article = Article.find_by_id(params[:id])
    article = Article.friendly.find(params[:id])
    article.update(article_params)
    redirect_to article
  end


  private

  def article_params
    params.require(:article).permit(:title, :image, :article_body, :short_description, :slug)
  end

  def js_css
    @js_css = {css: "article", js: "article"}
  end

  def admin
    unless current_user && current_user.admin?
      flash[:danger] = "How dare you use your guile tactics on us!"
      redirect_to '/cats'
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :js_css
  before_action :index_js_css, only: [:index]
  before_action :admin, only: [:edit, :update, :new, :create]

  def index
    @cats = Cat.paginate(page: params[:cat_page], per_page: 4 ).order('created_at ASC')
    @articles = Article.paginate(page: params[:page], per_page: 3 ).order('created_at ASC')
    @homepage = true
  end

  def show
    #@cat = Cat.find_by_id(params[:id])
    #@cat = Cat.friendly.find_by_id(params[:id])
    @cat = Cat.friendly.find(params[:id])
    puts "@cat"
    puts @cat
    @video_prefix = "https://www.youtube.com/embed/"
    @first_video = Video.where(cat_id: @cat).first
    @videos = Video.where(cat_id: @cat)[1..4]
    @cat_comments = CatComment.paginate(page: params[:page], per_page: 5 ).order('created_at DESC')
    @cat_comment = CatComment.new
    @twitterTitle = @cat.title
    @twitterURL = "https://www.felinesfancy.com/cats/#{@cat.slug}"
    @twitterImage = 'media/images/cats/' + @cat.image
    @twitterDescription = @cat.short_description
    @publication_date = "#{@cat.created_at.year}-#{@cat.created_at.month}-#{@cat.created_at.day}"
    @date_modified = "#{@cat.updated_at.year}-#{@cat.updated_at.month}-#{@cat.updated_at.day}"
  end

  def new
    @cat = Cat.new
  end

  def create
    cat = Cat.create!(cat_params)
    redirect_to cat
  end

  def edit
    #@cat = Cat.find_by_id(params[:id])
    @cat = Cat.friendly.find(params[:id])
  end

  def update
    #cat = Cat.find_by_id(params[:id])
    cat = Cat.friendly.find(params[:id])
    cat.update(cat_params)
    redirect_to cat
  end


  private

  def cat_params
    params.require(:cat).permit(:title, :image, :short_description, :article, :slug)
  end

  def js_css
    @js_css = {css: "cat", js: "cat"}
  end

  def index_js_css
    @index = {css: "article", js: "article"}
  end

  def admin
    unless current_user && current_user.admin?
      flash[:danger] = "How dare you use your guile tactics on us!"
      redirect_to '/cats'
    end
  end

end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cat_comments_helper.rb
module CatCommentsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="logo">
    <%= link_to root_path do %>
      <div class="logo__cat"></div>
    <% end %>
    <p class="slogan"><%= link_to "Feline's Fancy", root_path %></p>
  </div>
  <div class="website">
    <div class="buttons" data-controller="scroll">
      <% if @homepage %>
        <%= link_to( root_path, data: {action: "click->scroll#articles"} ) do %>
          <h4>Articles</h4>
        <% end %>
        <%= link_to( root_path, data: {action: "click->scroll#catBreeds"} ) do %>
          <h4>Cat Breeds</h4>
        <% end %>
        <%= link_to (new_cat_personality_test_path) do %>
          <h4>Cat Personality Test</h4>
        <% end %>
        <%= link_to (about_me_index_path) do %>
          <h4>About Me</h4>
        <% end %>
        <%= link_to new_contact_path do %>
          <h4>Feedback & Suggestions</h4>
        <% end %>
      <% else %>
        <%= link_to( root_path(scroll: "1") ) do %>
          <h4>Articles</h4>
        <% end %>
        <%= link_to( root_path(scroll: "2") ) do %>
          <h4>Cat Breeds</h4>
        <% end %>
        <%= link_to (new_cat_personality_test_path) do %>
          <h4>Cat Personality Test</h4>
        <% end %>
        <%= link_to (about_me_index_path) do %>
          <h4>About Me</h4>
        <% end %>
        <%= link_to new_contact_path do %>
          <h4>Feedback & Suggestions</h4>
        <% end %>
      <% end %>
    </div>
    <div class="search__feedback">
      <script async src="https://cse.google.com/cse.js?cx=007335270216527451082:dehwz3stake"></script>
      <div class="gcse-search"></div>
    </div>
    <div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= (@twitterTitle + " - FelinesFancy" if @twitterTitle) || "FelineFancy"  %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% if (Rails.env == 'production') %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138906419-3"></script>
    <% end %>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-138906419-3');
    </script>

    <meta name="p:domain_verify" content="a053fa730e1e5028be67c01f106129a1"/>

    <%# <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_pack_tag 'application', async: true %>
    <%= javascript_pack_tag 'application', async: true %>

    <% if @js_css %>
      <%= stylesheet_pack_tag @js_css[:css], async: true %>
      <%= javascript_pack_tag @js_css[:js], async: true %>
    <% end %>

    <% if @index %>
      <%= stylesheet_pack_tag @index[:css], async: true %>
      <%= javascript_pack_tag @index[:js], async: true %>
    <% end %>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-5374261406606651",
        enable_page_level_ads: true
      });
    </script>

    <% if @twitterTitle %>
      <meta name="Description" content="<%= @twitterDescription %>">
      <meta property="fb:app_id" content="2658928914117851">
      <meta property="og:type" content="article" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta property="og:title" content="<%= @twitterTitle %>" />
      <meta property="og:url" content=<%= @twitterURL %> />
      <meta property="og:image" content="http://www.felinesfancy.com<%= asset_pack_path @twitterImage %>"  />
      <meta name="twitter:image" content="http://www.felinesfancy.com<%= asset_pack_path @twitterImage %>">
      <meta property="og:description" content="<%= @twitterDescription %>" />
      <meta property="article:published_time" content="2019-08-21T00:01:56+00:00" />
      <meta property="article:author" content="Feline's Fancy" />
    <% end %>

    <% if @twitterTitle %>
      <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "Article",
          "headline": "<%= @twitterTitle %>",
          "author": "Cat Lover",
          "image": "http://www.felinesfancy.com<%= asset_pack_path @twitterImage %>",
          "genre": "pets",
          "datePublished": "<%= @publication_date %>",
          "dateModified": "<%= @date_modified %>",
          "publisher": {
            "@type": "Organization",
            "name": "Felines Fancy",
            "logo": {
              "@type": "ImageObject",
              "url": "http://www.felinesfancy.com/packs/media/images/header/cat-89b4ce7373715a13d908045ab7e67482.png"
            }
          },
          "url": "<%= @twitterURL %>",
          "description": "<%= @twitterDescription %>"
        }
      </script>
      <meta name="description" content="<%= @twitterDescription %>">
    <% else %>
      <script type="application/ld+json">
        {
          "@context": "http://schema.org",
          "@type": "WebPage",
          "name": "Felines Fancy",
          "description": "All about domestic cats, cat breed profiles, and articles about taking care of your cat"
        }
      </script>
      <meta name="description" content="All about domestic cats, cat breed profiles, and articles about taking care of your cat">
    <% end %>


  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>

    <script src="//assets.pinterest.com/js/pinit.js"
      type="text/javascript" async defer
      data-pin-hover="true">
    </script>
  </body>
</html>